name: 'monkey-release'
description: Validate and handle releases
inputs:
  repo_token:
    description: 'The GITHUB_TOKEN for this repo'
    required: true
  base_branch:
    description: 'Name of the base branch'
    required: true
    default: 'master'
  head_branch:
    description: 'Name of the head branch'
    required: true
    default: 'dev'
  create_status:
    description: 'If the action state should be created as a status'
    required: true
    default: true
  status_name:
    description: 'Name of the status created by this action'
    required: true
    default: 'Monkey Release'
  release_pattern:
    description: |
      'Pattern to validate title against.
       If it contains any of the named capture groups <year>, <month>, <day> calver validation will occur.'
    required: true
    default: '^(?<year>[0-9]{4})\.(?<month>[0-9]{2})\.(?<day>[0-9]{2})-\d+$'
  tag_prefix:
    description: 'Prefix to use when tagging release'
    required: true
    default: 'release/'
  approve_releases:
    description: 'If release reviews should be approved or just commented upon'
    required: true
    default: true
  prerelease:
    description: 'Creates a prerelease instead of release'
    required: false
    default: false
  validate:
    description: 'Validate title and description of pull request'
    required: false
    default: true
  tag_transformer:
    description: 'Transformer to use to change the tag name.'
    required: false
    default: 'title'
  release_label:
    description: 'Label to add to release PR.'
    default: 'release'
  valid_release_message:
    description: 'Message to comment with on valid release PRs.'
    default: 'Valid release 🍌'
  generate_body:
    description: 'Use githubs native release note generator.'
    default: false
outputs:
  release:
    description: 'Name of release'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'truck'
  color: 'orange'
