name: Test

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run lint
    - run: npm test

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Validate build
        shell: bash
        run: |
          set -e
          npm ci
          git add -A
          npm run package
          if [ -n "$(git status --porcelain -- dist)" ]; then
            echo "::error::Build result differs. Run 'npm run package' then commit and push any changes"
            git status --porcelain -- dist
            exit 1
          fi
